-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- local function augroup(name)
--   return vim.api.nvim_create_augroup("lazyvim_" .. name, { clear = true })
-- end
--
-- -- Remove comment on newlining (currently not working)
-- vim.api.nvim_create_autocmd("BufEnter", {
--   group = augroup("new_format"),
--   callback = function()
--     vim.opt.formatoptions = vim.opt.formatoptions - { "c", "r", "o" }
--   end,
-- })
